"""Pin the vendored pose helpers against the converter that produced them.

`src/vla/controller/pose.py` is a verbatim copy of
`src/viam_sequence_to_lerobot/pose.py` at
`viam-labs/viam-sequence-to-lerobot@eaa1937` (branch `action-space-delta-ee`).
A copy is only as good as the thing that proves it is still a copy, so the
golden vectors below were generated by *executing that file* and are asserted
against this module's copy here. Regenerate them the same way if the converter
ever changes:

    python - <<'PY'
    import importlib.util, json
    spec = importlib.util.spec_from_file_location("ref", "<converter>/pose.py")
    ref = importlib.util.module_from_spec(spec); spec.loader.exec_module(ref)
    print(json.dumps([list(ref.pose_state({"pose": p})) for p in POSES]))
    PY

The two tests at the bottom are the point of the whole file. Both introduce a
mistake this module has to be immune to, and both must FAIL if the production
code ever makes it. A test that passes either way would be worse than no test,
because it would read as coverage.
"""

from __future__ import annotations

import numpy as np
import pytest
from scipy.spatial.transform import Rotation

from vla.controller.pose import (
    ACTION_NAMES,
    STATE_NAMES,
    orientation_vector,
    pose_rotation,
    pose_state,
    state_compose,
    state_delta,
    state_rotation,
)

# A near-vertical tool pose as the xarm reports it, a generic off-axis pose,
# and the identity. Order matters only in that the first is the regime the
# recorded dataset sits in.
POSES = [
    {"x": 305.4, "y": -12.75, "z": 231.9,
     "o_x": 0.0139, "o_y": -0.0271, "o_z": -0.9995, "theta": 41.7},
    {"x": -100.0, "y": 250.5, "z": 480.25,
     "o_x": 0.5773502691896258, "o_y": 0.5773502691896258,
     "o_z": 0.5773502691896258, "theta": -120.0},
    {"x": 0.0, "y": 0.0, "z": 100.0, "o_x": 0.0, "o_y": 0.0, "o_z": 1.0, "theta": 0.0},
]

# Per-tick deltas at the recorded median and p99 magnitudes, plus a zero.
DELTAS = [
    [9.31, -2.0, 0.5, 0.0142, -0.003, 0.0071],
    [-28.4, 14.2, -7.1, -0.0807, 0.0301, 0.0119],
    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
]

GOLDEN_STATES = [
    [305.4, -12.75, 231.9,
     0.25131573681340424, 0.9678053401860794, 0.013900501330621543,
     0.9676379716235207, -0.250883026320044, -0.027100977414377246],
    [-100.0, 250.5, 480.25,
     0.40824829046386324, 0.7071067811865475, 0.5773502691896258,
     -0.816496580927726, 2.220446049250313e-16, 0.5773502691896258],
    [0.0, 0.0, 100.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
]

GOLDEN_COMPOSED = [
    [314.71, -14.75, 232.4,
     0.25820117719050256, 0.96609098865787, -0.000594753308733622,
     0.9657507147417713, -0.2581264789219709, -0.026387077426339993],
    [-128.4, 264.7, 473.15,
     0.39794688453547067, 0.6529779816924957, 0.6444051772862378,
     -0.8337025644899074, -0.03573503622003715, 0.551056295807701],
    [0.0, 0.0, 100.0, 1.0, 0.0, 0.0, 0.0, 1.0, 0.0],
]

GOLDEN_ORIENTATION_VECTORS = [
    {"o_x": 0.013900501330621547, "o_y": -0.027100977414377253,
     "o_z": -0.9995360489176681, "theta": 41.699999999999996},
    {"o_x": 0.5773502691896258, "o_y": 0.577350269189626,
     "o_z": 0.5773502691896257, "theta": -119.99999999999999},
    {"o_x": 0.0, "o_y": 0.0, "o_z": 1.0, "theta": -0.0},
]


def test_state_layout_is_the_documented_nine_and_six():
    assert STATE_NAMES == ["x", "y", "z", "r00", "r01", "r02", "r10", "r11", "r12"]
    assert ACTION_NAMES == ["dx", "dy", "dz", "drx", "dry", "drz"]


@pytest.mark.parametrize("pose, golden", list(zip(POSES, GOLDEN_STATES)))
def test_pose_state_matches_the_converter(pose, golden):
    np.testing.assert_allclose(pose_state({"pose": pose}), golden, rtol=1e-12, atol=1e-12)


@pytest.mark.parametrize("pose, delta, golden", list(zip(POSES, DELTAS, GOLDEN_COMPOSED)))
def test_state_compose_matches_the_converter(pose, delta, golden):
    composed = state_compose(pose_state({"pose": pose}), np.asarray(delta))
    np.testing.assert_allclose(composed, golden, rtol=1e-12, atol=1e-12)


@pytest.mark.parametrize("pose, golden", list(zip(POSES, GOLDEN_ORIENTATION_VECTORS)))
def test_orientation_vector_matches_the_converter(pose, golden):
    vector = orientation_vector(state_rotation(np.asarray(pose_state({"pose": pose}))))
    for key, expected in golden.items():
        assert vector[key] == pytest.approx(expected, abs=1e-12)


@pytest.mark.parametrize("pose, delta", list(zip(POSES, DELTAS)))
def test_compose_and_delta_are_exact_inverses(pose, delta):
    """The property the whole action space rests on.

    The dataset was built by `state_delta`; inference runs `state_compose`. If
    they were not inverses, every commanded pose would be wrong by whatever
    the two disagreed about, in a way no single-tick test would notice.
    """
    state = pose_state({"pose": pose})
    recovered = state_delta(state, state_compose(state, np.asarray(delta)))
    np.testing.assert_allclose(recovered, delta, rtol=1e-9, atol=1e-9)


def test_state_rotation_accepts_any_six_numbers():
    """A policy's raw output carries no orthogonality constraint.

    Gram-Schmidt is what makes an unconstrained 6-number rotation head usable
    at all; without it a checkpoint whose output drifts off SO(3) by 1e-3 --
    which is normal -- would need rejecting or renormalizing somewhere else.
    """
    rotation = state_rotation(np.array([0.0, 0.0, 0.0, 2.0, 0.1, 0.0, 0.3, 5.0, 0.2]))
    np.testing.assert_allclose(
        rotation.as_matrix() @ rotation.as_matrix().T, np.eye(3), atol=1e-12
    )
    assert rotation.as_matrix().shape == (3, 3)
    np.testing.assert_allclose(np.linalg.det(rotation.as_matrix()), 1.0, atol=1e-12)


def test_state_rotation_refuses_a_degenerate_first_row():
    with pytest.raises(ValueError, match="zero length"):
        state_rotation(np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0]))


def test_state_rotation_refuses_parallel_rows():
    with pytest.raises(ValueError, match="parallel"):
        state_rotation(np.array([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 2.0, 0.0, 0.0]))


def test_pose_rotation_refuses_a_zero_orientation_vector():
    with pytest.raises(ValueError, match="zero length"):
        pose_rotation({"o_x": 0.0, "o_y": 0.0, "o_z": 0.0, "theta": 30.0})


def test_pose_rotation_goes_through_the_sdk_not_hand_rolled_quaternions():
    """Guard the one conversion nobody can eyeball.

    scipy orders a quaternion `(x, y, z, w)` and the Viam SDK `(w, i, j, k)`.
    Reordering by hand gets a *valid* rotation that is simply not the one the
    pose describes, and nothing downstream can tell. Recomputing the rotation
    straight from the SDK's own quaternion is the independent check.
    """
    from viam.spatialmath import OrientationVector

    pose = POSES[0]
    quaternion = OrientationVector(
        pose["o_x"], pose["o_y"], pose["o_z"], np.deg2rad(pose["theta"])
    ).to_quaternion()
    expected = Rotation.from_quat(
        [quaternion.i, quaternion.j, quaternion.k, quaternion.w]
    )
    np.testing.assert_allclose(
        pose_rotation(pose).as_matrix(), expected.as_matrix(), atol=1e-12
    )


# ---------------------------------------------------------------------------
# The two silent-failure canaries.
#
# Each recreates a mistake locally and asserts the correct answer is NOT what
# the mistake produces. If either of these ever passes with the mistake made
# in `pose.py` itself, it has stopped being a test. Their separation values
# are asserted too, so a future pose that happened to make rows == columns (or
# left == right) would fail loudly here rather than quietly stop testing
# anything.
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("pose", POSES[:2])
def test_transposing_the_rotation_changes_the_state(pose):
    """The state holds matrix ROWS. Columns are a different, plausible answer."""
    rotation = pose_rotation(pose).as_matrix()
    rows = rotation[:2, :].reshape(6)
    columns = rotation[:, :2].T.reshape(6)

    separation = float(np.abs(rows - columns).max())
    assert separation > 1e-3, (
        "this pose no longer distinguishes rows from columns, so it cannot "
        "guard the transpose; pick another"
    )
    np.testing.assert_allclose(pose_state({"pose": pose})[3:], rows, atol=1e-12)
    assert not np.allclose(pose_state({"pose": pose})[3:], columns, atol=1e-6)


@pytest.mark.parametrize("pose, delta", list(zip(POSES[:2], DELTAS[:2])))
def test_left_multiplying_the_delta_changes_the_result(pose, delta):
    """The delta is body-frame: `R_t * dR`, never `dR * R_t`.

    Left-multiplying applies the rotation in the world frame. The tool still
    moves smoothly and still ends up somewhere legal -- just about the wrong
    axes -- so nothing but this assertion catches it.
    """
    state = pose_state({"pose": pose})
    current = state_rotation(state)
    increment = Rotation.from_rotvec(np.asarray(delta[3:6]))

    body_frame = (current * increment).as_matrix()[:2, :].reshape(6)
    world_frame = (increment * current).as_matrix()[:2, :].reshape(6)

    separation = float(np.abs(body_frame - world_frame).max())
    assert separation > 1e-4, (
        "this delta no longer distinguishes body-frame from world-frame "
        "composition, so it cannot guard the multiply order; pick another"
    )
    composed = state_compose(state, np.asarray(delta))
    np.testing.assert_allclose(composed[3:], body_frame, atol=1e-12)
    assert not np.allclose(composed[3:], world_frame, atol=1e-6)
